---
title: "ROC及逻辑回归的ROC绘制"
output:
  html_document: 
    number_sections: yes
    theme: cerulean
    toc: yes
    toc_float:
      print: no
    toc_depth: 5
vignette: >
  %\VignetteIndexEntry{ROC及逻辑回归的ROC绘制}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

`map_common_roc`函数为绘制roc图使用。

`map_common_logroc`函数为绘制逻辑回归后roc图使用。底层使用`map_common_roc`函数。

## 数据准备

数据为dataframe格式,数据格式如下：

```{r}
test <- matrix(abs(rnorm(200)), 20, 10)
test <- as.data.frame(test)
colnames(test) <- paste("Test", 1:10, sep = "")
rownames(test) <- paste("Gene", 1:20, sep = "")
colgroup <- data.frame(Group = c(rep("A",5),rep("B",5)))
rownames(colgroup) <- paste("Test", 1:10, sep = "")
test <- rbind(t(colgroup),test)
```

```{r include = FALSE,warning = FALSE,results = 'hide'}
library("DT")
library("lmbio")
```

```{r echo=FALSE}
datatable(test,options = list(scrollX = TRUE))
```

## 绘图使用

```{r fig.height = 6,fig.width = 6,warning = FALSE,message = F}
plot <- map_common_roc(filename = test[1:2,],
                       imagetype = NA,
                       saveroc = F) # 是否保存roc结果数据
```

```{r fig.height = 6,fig.width = 6,warning = FALSE,message = F,results = "hide"}
plot <- map_common_roc(filename = test[1:3,],
                       imagetype = NA,
                       saveroc = F) # 是否保存roc结果数据
```

## 进阶使用

### 示例1 多roc叠加

```{r fig.height = 6,fig.width = 6,warning = FALSE,message = F,results = "hide"}
plot <- map_common_roc(filename = test[1:4,],
                       number = 3,
                       imagetype = NA,
                       saveroc =F)
```

### 示例2 不显示AUC

```{r fig.height = 6,fig.width = 6,warning = FALSE,message = F,results = "hide"}
plot <- map_common_roc(filename = test[1:2,],
                       imagetype = NA,
                       AUC = F,
                       saveroc = F)
```

### 示例3 计算逻辑回归roc

```{r fig.height = 6,fig.width = 6,warning = FALSE,message = F,results = "hide"}
plot <- map_common_logroc(filename = test[1:4,],
                          imagetype = NA,
                          saveroc = F) # 是否保存roc结果数据
```

```{r fig.height = 6,fig.width = 6,warning = FALSE,message = F,results = "hide"}
plot <- map_common_logroc(filename = test[1:4,],
                          imagetype = NA,
                          all = T,
                          saveroc = F) # 是否保存roc结果数据
```

### 示例4 随机组合进行逻辑回归roc计算

如果特征有10个，num设为4，就会在10个特征中将4个组合全部一起计算。

```{r fig.height = 6,fig.width = 6,warning = FALSE,message = F,results = "hide"}
plot <- map_common_logroc(filename = test[1:4,],
                          imagetype = NA,
                          num = 2,
                          saveroc = F) # 是否保存roc结果数据
```
<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;"></div>