$schema: "https://json-schema.org/draft/2020-12/schema"
description: 多元统计分析
required:
    - path
    - compare
properties:
    path:
        type: object
        properties:
            datafile:
                type: string
                default: "oecloud/rawdata/datafile.txt"
                description: 数据来源文件
            classfile:
                type: string
                default: "oecloud/rawdata/classfile.yaml"
                description: 分组信息来源文件
            infofile:
                type: string
                default: "oecloud/rawdata/infofile.txt"
                description: 分组信息来源文件
            comparefile:
                type: string
                default: "oecloud/rawdata/compare.yaml"
                description: 分组信息来源文件            
            diff_ana_rds_savepath:
                type: string
                default: "oecloud/diff_ana_vip"
                description: 多元统计运算结果保存路径
            diff_filter_rds_savepath:
                type: string
                default: "oecloud/diff_filter"
                description: 多元统计运算结果保存路径
            mulstatistics_rds_savepath:
                type: string
                default: "oecloud/mulstatisticsanalyst"
                description: 多元统计运算结果保存路径
            enrich_xls_savepath:
                type: string
                default: "oecloud/enrich"
                description: 多元统计运算结果保存路径
    params:
        type: object
        properties:
            enrich:
                type: object
                properties:
                    database:
                        type: string
                        default: 'background/'
                        description: 富集背景文件路径
                    keggdb:
                        type: string
                        default: '/data/hstore3/database/kegg/'
                        description: keggmap图所有物种存放位置
                    org:
                        type: string
                        default: 'hsa'
                        description: kegg物种拉丁名缩写
            diff_filter:
                type: object
                properties:
                    log:
                        type: boolean
                        default: false
                        description: 是否经过log处理
                    fcfilter:
                        type: array
                        default:
                            - 1.2
                            - 1.5
                            - 2
                        description: FC筛选标准
                    fcfiltertype:
                        type: string
                        default: '+-'
                        description: 上下调筛选情况
                    errorptofcfilter:
                        type: number
                        default: 2
                        description: VIP失败后FC筛选标准
                    vipfilter:
                        type: number
                        default: 0
                        description: VIP筛选标准
                    pfilter:
                        type: number
                        default: 0.05
                        description: p-value筛选标准
                    adjpfilter:
                        type: number
                        default: 0
                        description: adjp-value筛选标准
    compare: 
        type: object
        patternProperties:
            ".*":
                type: object
                required:
                    - rawname
                    - group
                properties:
                    rawname:
                        type: string
                        description: 原始比较组名称
                    group: 
                        type: array
                        description: 比较组组别
