---
title: "空间代谢组分析流程"
output:
  html_document: 
    number_sections: yes
    theme: cerulean
    toc: yes
    toc_float:
      print: no
    toc_depth: 5
vignette: >
  %\VignetteIndexEntry{空间代谢组分析流程}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# 整体分析流程

AFAI测试数据路径:`r lmbio::databasepath("database/test/2023-03-21空代新流程测试",exist = F)`

Waters测试数据路径:`r lmbio::databasepath("database/test/2023-04-06waters数据处理",exist = F)`

## 分析流程

```bash
# 1. 创建文件及整理原始数据


# 2. 数据转格式
spatialmetabolism_1.0_rawtoimzml --ratio 2

# 备注ratio参数默认为2，如果使用QE HF仪器ratio参数为2.5，请将上述相关脚本修改为以下脚本调用
spatialmetabolism_1.0_rawtoimzml --ratio 2.5

# 备注如果是waters仪器
spatialmetabolism_1.0_rawtoimzml --waters --resolution 20 --ratio 2

# spatialmetabolism_1.0_rawtoimzml.R包含以下流程:
spatialmetabolism_1.1_SpacemetaFileRename_waters
spatialmetabolism_1.2-1.4_watersdata # waters仪器数据处理
spatialmetabolism_1.1_SpacemetaFileRename # 文件名修正
spatialmetabolism_1.2_convertrawtoimzml.sh # 转格式
spatialmetabolism_1.3_mulimzmltoone # 多个imzml合并
spatialmetabolism_1.4_moverawfile # 移动原始数据
spatialmetabolism_1.5_createregistration # 创建登记单及脚本
spatialmetabolism_1.6_compressandcluster # 压缩聚类

# 3. 手动背景区域选择
# 在项目登记单背景信息中填写
# 填写完成后运行以下脚本
spatialmetabolism_2.0_rebg_compressandcluster

# 4. 手动样本区域选择
# 使用浏览器登录http://10.100.10.42:8719的Rstudio
# 使用RejectBG-Manual.R脚本进行扣除背景

# 5. 添加项目登记单

# 6. 数据预处理
spatialmetabolism_3.0_PreDeal -st 小鼠_肺

## 如果是中药定性项目
spatialmetabolism_3.0_PreDeal -od tcm -st 中药

## 如果是waters仪器
spatialmetabolism_3.0_PreDeal --waters --normethod none --resolution 20 --tolerance 30 --ppm 10 -st 小鼠_肺

## 输入批次信息
spatialmetabolism_3.0_PreDeal -st 小鼠_肺 -sb 1:kidney1,qc_data1 2:kidney2,qc_data2 3:kidney3,qc_data3 4:kidney4,qc_data4 5:kidney4,qc_data5
 
# spatialmetabolism_3.0_PreDeal.R包含以下流程:
spatialmetabolism_3.1_ReferenceMZ # 峰对齐
spatialmetabolism_3.2_Normalization # 归一化(包含条纹校正，默认不开启)
spatialmetabolism_3.3_Qualitative # 定性(包含包埋胶离子识别)
spatialmetabolism_3.3_Qualitative_2023 # 定性_2023版本
spatialmetabolism_3.4_rmbgmz # 背景离子识别
spatialmetabolism_3.5_PreDeal # 峰提取(包含条纹校正，默认开启)
spatialmetabolism_3.6_Combat # 批次校正
spatialmetabolism_3.7_MulanaCluster # 聚类分析
spatialmetabolism_3.8_GetData # 数据提取(样本整体提取、根据MSIreader提取、根据聚类结果提取、区域组合提取)
spatialmetabolism_3.9_SpaceAnalysisData # 差异比较分析
spatialmetabolism_3.9_SpaceAnalysisData_2023 # 差异比较分析_2023版本
spatialmetabolism_3.10_makereport # 生成报告

# 7. 发送客户数据

```

### 优化记录

#### 2023-09-12优化内容

1. QC质控的流程添加
2. 背景强度筛选的阈值降低到200

#### 2023-09-04优化内容

1. 调整空代离子筛选标准，由最强离子的1/10000筛选调整为1000和500的固定值

#### 2023-08-17优化内容

1. 空代部分参数及bug修复、暂时关闭背景离子归一化、对齐容差调整为10ppm和对齐窗口范围由2调整为3

#### 2023-08-14优化内容

1. 针对harmony和Seurat批次校正添加QC对齐流程

#### 2023-08-09优化内容

1. 空代部分函数无效传参修复

#### 2023-04-17优化内容

1. 增加waters的空代数据处理流程

#### 2023-02-21优化内容

1. 新增`readimzml`及`saveimzml`，并添加`ibr`格式文件进行空代信息存储
2. 优化了空代定性流程，增加正离子包埋胶离子识别功能
3. 增加空代运行记录内容，保存调用脚本及命令、运行镜像、运行人员、运行时间
4. 文件将以链接形式进行存储，所有中间过程文件将以“目录-时间-人员-随机码”方式存储，防止误删
5. 空代大分析流程拆解为小流程，可单独运行小流程进行运行
6. 将比较分析中all及mean的文件标识修改为pixel_level和sample_level
7. 增加过程中样本转向、镜像操作的记录，将用于预处理使用转向、镜像操作

### 主要目录说明（重要）

#### 现仅有sample目录

| 目录     | 内容     |
| -------- | -------- |
| final    | 最终imzML文件  |
| adjustdata  | 批次矫正后数据  |
| qualitative | 定性结果  |
| peak | 峰对齐结果  |
| cluster  | 聚类及降维中间数据  |
| imzml    | 最初始数据  |
| area    | 区域数据  |

#### sample/area下目录

| 目录     | 内容     |
| -------- | -------- |
| data     | 选取数据及中间文件  |
| map      | 选区可视化图  |
| select   | MSIReader选区文件  |


## 操作流程（重要）

### 质谱数据处理，将raw格式转化为imzML格式

```bash
# 使用Xshell或其他ssh软件登录10.100.10.42:8019

# 创建项目分析文件夹
mkdir filename
cd filename

# 将空间质谱数据放入raw文件夹中

# 如是是AFAI的raw文件格式数据，根据正负离子创建文件夹（neg、pos注意小写），后将根据玻片或样本创建文件夹
.filename
└── raw
	├── neg
	|	├── slide1
	|	|	├── slide1-001.raw
	|	|	├── slide1-002.raw
	|	|	└── ···
	|	├── slide2
	|	|	├── slide2-001.raw
	|	|	├── slide2-002.raw
	|	|	└── ···
	|	└── ···
	└── pos
		├── slide1
		|	├── slide1-01.raw
		|	├── slide1-002.raw
		|	└── ···
		├── slide2
		|	├── slide2-001.raw
		|	├── slide2-002.raw
		|	└── ···
		└── ···

# 如是是waters的imzml文件格式数据，根据正负离子创建文件夹（neg、pos注意小写）后存放
.filename
└── raw
	├── neg
	|	├── slide1.imzml
	|	├── slide1.ibd
	|	└── ···
	└── pos
		├── slide1.imzml
		├── slide1.ibd
		└── ···

# slide命名规则：以字母及数字组合

# 空间质谱数据整理完毕后运行以下脚本
spatialmetabolism_1.0_rawtoimzml --ratio 2
 
# 备注ratio参数默认为2，如果使用QE HF仪器ratio参数为2.5，请将上述相关脚本修改为以下脚本调用
spatialmetabolism_1.0_rawtoimzml --ratio 2.5

# 备注如果是waters仪器
spatialmetabolism_1.0_rawtoimzml --waters --resolution 20 --ratio 2
```

### 手动判别背景区域

```bash
# 在项目登记单背景信息中填写
# 保证不要选到样本区域
# 填写完成后运行以下脚本
spatialmetabolism_2.0_rebg_compressandcluster
```  

### 手动样本与质控区域选择

```bash
# 使用浏览器登录录http://10.100.10.42:8719的Rstudio
# 使用RejectBG-Manual.R脚本进行扣除背景
# 同时可进行旋转操作
```

### 背景扣除、峰对齐、峰筛选、标准化、平滑处理、聚类、绘图、搜库定性

```bash
# 使用Terminal运行以下脚本
spatialmetabolism_3.0_PreDeal -st 小鼠_肺

```

### 客户确认选区(MSiReader软件选区使用说明)

```bash
# 客户选区数据
samplename-areaname-mode.txt
samplename：样本名
areaname：区域名
mode：neg/pos（正负离子模式）

# 客户选区数据存放位置
.filename
  └── sample
    └── msireader # 客户选区数据
  		├── sample1-area1-neg.txt
  		├── sample1-area1-pos.txt
  		└── ···

# 使用Xshell或其他ssh软件登录192.168.10.200:8080
# 针对客户选区进行数据处理
spatialmetabolism_3.8_GetData
```

## 项目登记单填写

### 项目登记单

| 项目登记单 |                    |
| ---------- | ------------------ |
| 项目编号   |                    |
| 客户单位   |                    |
| 项目类别   | 空间代谢组         |
| 处理类别   | 内部数据定性加分析 |
| 仪器平台   | QE                 |
| 物种       |                    |
| 样本类型   |                    |
| 映射简写   |                    |
| X轴扫描速度| 0.2                |
| 轴步进间距 | 0.1                |
| 分辨率     | 100*100            |
| 仪器分辨率 | 70000              |
| 执行编码   |                    |

### 背景信息

| 玻片名 | 模式    | 聚类  |
| ------ | ------- | ----- |
| slide1 | neg     | 1+2   |
| slide1 | pos     | 3     |
| slide2 | neg     | 4     |
| slide2 | pos     | 5+6+7 |

### 样本信息

| 样本信息 | 样本编号 |
| -------- | -------- |
| group1   | sample1  |
| group1   | sample2  |
| group2   | sample3  |
| group2   | sample4  |


### 分组信息

| 分组   | 样品    | 选区  | 模式 |
| ------ | ------- | ----- | ---- |
| group1 | sample1 | area1 | neg  |
| group1 | sample1 | area1 | pos  |
| group2 | sample1 | area1 | neg  |
| group2 | sample1 | area1 | pos  |


### 比较组信息

| 实验组 | 对照组 | 比较组        | 模式 | 比较模式 |
| ------ | ------ | ------------- | ---- | -------- |
| group1 | group2 | group1/group2 | neg  | all      |
| group1 | group2 | group1/group2 | pos  | all      |
| group1 | group2 | group1/group2 | neg  | mean     |
| group1 | group2 | group1/group2 | pos  | mean     |
| group1 | group2 | group1/group2 | neg  | pixel_level      |
| group1 | group2 | group1/group2 | pos  | pixel_level      |
| group1 | group2 | group1/group2 | neg  | sample_level     |
| group1 | group2 | group1/group2 | pos  | sample_level     |

### 聚类选区

| 分组   | 样品    | 选区  | 模式 | 聚类 | 聚类来源 |
| ------ | ------- | ----- | ---- | ---- | -------- |
| group1 | sample1 | area1 | neg  | 1+2  | all      |
| group1 | sample1 | area1 | pos  | 1+2  | single   |
| group2 | sample1 | area1 | neg  | 3+4  | all      |
| group2 | sample1 | area1 | pos  | 3+4  | single   |


### 多区域选区

| 分组   | 样品    | 选区        | 模式 | 交集        | 差集  |
| ------ | ------- | ----------- | ---- | ----------- | ----- |
| group1 | sample1 | area        | all  | area1+area2 |       |
| group1 | sample  | area1-area2 | pos  | area1       | area2 |


### 趋势分析

| 趋势分析分组         | 模式 |
| -------------------- | ---- |
| group1/group2/group3 | both |
|                      | neg  |
|                      | pos  |

<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;"></div>
