$schema: "https://json-schema.org/draft/2020-12/schema"
description: 多元统计分析
required:
    - path
    - compare
properties:
    path:
        type: object
        required:
            - datafile
            - classfile
        properties: &id001
            datafile:
                type: string
                description: 数据来源文件
            classfile:
                type: string
                description: 分组信息来源文件
            config_savepath:
                type: string
                default: "oecloud/config"
                description: config保存路径
            mulstatistics_rds_savepath:
                type: string
                default: "oecloud/mulstatisticsanalyst"
                description: 多元统计运算结果保存路径
    compare: 
        type: object
        patternProperties:
            ".*":
                type: object
                required:
                    - rawname
                    - group
                properties:
                    rawname:
                        type: string
                        description: 原始比较组名称
                    group: 
                        type: array
                        description: 比较组组别
                    OPLS-DA:
                        type: object
                        properties: 
                            scaleC:
                                type: string
                                default: "pareto"
                                description: 归一化算法
                                enum:
                                    - "standard"
                                    - "pareto"
                                    - "none"
                                    - "center"
                            predI:
                                type: integer
                                default: 1
                                description: 主成分数量
                            orthoI:
                                type: integer
                                default: -1
                                description: 正交主成分数量
                            permI:
                                type: integer
                                default: 200
                                description: 响应检测排序数量
                            log10L:
                                type: boolean
                                default: false
                                description: 是否log10处理
                            amount:
                                type: integer
                                default: 3
                                description: 最小主成分数量
